sudo: required

services:
  - docker

before_install:
  - docker build -t ewfnz/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ewfnz/client-test yarn test -- --coverage

after_success:
  - docker build -t ewfnz/react-nginx-client:prod ./client
  - docker build -t ewfnz/express-worker:prod ./client
  - docker build -t ewfnz/express-server:prod ./server
  - docker build -t ewfnz/nginx-router:prod ./nginx
#LogIn to the dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push those builded images to dockerhub
  - docker push ewfnz/react-nginx-client:prod
  - docker push ewfnz/express-worker:prod
  - docker push ewfnz/express-server:prod
  - docker push ewfnz/nginx-router:prod

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "rexpgredis-1"
  env: "Rexpgredis1-env"
  bucket_name: "elasticbeanstalk-us-east-1-748388487233"
  bucket_path: "rexpgredis"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"


