sudo: required

services:
  - docker

before_install:
  - docker build -t ewfnz/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ewfnz/client-test yarn test -- --coverage

after_success:
  - docker build -t ewfnz/react-nginx-client:prod ./client
  - docker build -t ewfnz/express-worker:prod ./client
  - docker build -t ewfnz/express-server:prod ./server
  - docker build -t ewfnz/nginx-router:prod ./nginx
#LogIn to the dockerhub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Push those builded images to dockerhub
  - docker push ewfnz/react-nginx-client:prod
  - docker push ewfnz/express-worker:prod
  - docker push ewfnz/express-server:prod
  - docker push ewfnz/nginx-router:prod

